### ISSUE TITLE
missing "superpowers-extra"

### ISSUE THREAD

**Issue by kumavis** [superpowers/superpowers-html5.com#2]
webpage contains link to https://github.com/superpowers-extra, which is missing

**Comment by elisee** [comment]
Thanks, looks like we forgot to create the organization ^_^. Just did it and added a temporary link to https://bitbucket.org/sparklinlabs/profile/repositories?search=superpowers- until we migrate all the repositories from Bitbucket to GitHub. Keeping this issue open so we don't forget!

**Comment by kumavis** [comment]
:+1: thank you for open sourcing this great stuff! I know you've all worked so hard on it.

**Comment by kumavis** [comment]
:clap:
