### ISSUE TITLE
sparklinlabs.itch.io crashes Safari on iPad

### ISSUE THREAD

**Issue by peterennis** [superpowers/superpowers-html5.com#3]
A problem occurred with this web page so it was reloaded.
iPad, Safari, iOS 9.2

**Comment by elisee** [comment]
Not much we can do about that I'm afraid. Maybe it's loading too many images or GIFs? Maybe you can report it to the developers of itch.io on https://github.com/leafo/itch.io/issues/new with as many details as possible? e.g. whether it crashes every time and if it works after the automated reloaded, also which generation of iPad you're using.
